name: draw_graph
description: >-
  Do you want to display a graph in your app? This package can help.
  It has a widget that draws line graph for you.
version: 1.0.0
homepage: https://github.com/malihanan/draw_graph.git

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: